apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrition-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nutrition-service
  template:
    metadata:
      labels:
        app: nutrition-service
    spec:
      containers:
        - name: nutrition-service
          image: ratgym/nutrition-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3004
          env:
            # RabbitMQ
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"

            # LLaMA
            - name: LLAMA_BASE_URL
              value: http://llama-service:11434

            # App
            - name: NODE_ENV
              value: production
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nutrition-service
spec:
  selector:
    app: nutrition-service
  ports:
    - port: 3004
      targetPort: 3004
  type: ClusterIP
