apiVersion: v1
kind: ConfigMap
metadata:
  name: ratgym-config
data:
  RABBITMQ_URL: "amqp://rabbitmq:5672"
  USER_SERVICE_URL: "http://user-service:3001"
  SAGA_ORCHESTRATOR_URL: "http://saga-orchestrator:3010"
  API_GATEWAY_URL: "http://api-gateway:3000"
  
  # Service Queues
  USER_SERVICE_QUEUE: "user_service_queue"
  ROUTINE_SERVICE_QUEUE: "routine_service_queue"
  NUTRITION_SERVICE_QUEUE: "nutrition_service_queue"
  CLASS_SERVICE_QUEUE: "class_service_queue"
  NOTIFICATION_SERVICE_QUEUE: "notification_service_queue"
  SAGA_ORCHESTRATOR_QUEUE: "saga_orchestrator_queue"
